/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.3.0   2025-05-13

The MIT License (MIT)
Copyright (c) 2019 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

/* Includes */
#include "stm32f3xx.h"
#include <stdio.h>  // Для sprintf
#include <inttypes.h>

void init_usart(void);
void delay_ms(uint32_t ms); // функция задержки, если потребуется

// Исправленная версия init_usart()
void init_usart(void) {
    RCC->AHBENR |= RCC_AHBENR_GPIOAEN;

    // Настройка PA2 (TX) и PA3 (RX) в альтернативный режим AF7
    GPIOA->MODER &= ~(GPIO_MODER_MODER2 | GPIO_MODER_MODER3); // Сброс битов
    GPIOA->MODER |= GPIO_MODER_MODER2_1 | GPIO_MODER_MODER3_1; // Альтернативный режим

    GPIOA->AFR[0] &= ~((0xF << 8) | (0xF << 12)); // Сброс AFR для PA2 и PA3
    GPIOA->AFR[0] |= (7 << 8) | (7 << 12); // AF7 для PA2 и PA3

    RCC->APB1ENR |= RCC_APB1ENR_USART2EN; // Тактирование USART2

    USART2->BRR = SystemCoreClock / 115200;

    USART2->CR1 |= USART_CR1_TE | USART_CR1_RE;
    USART2->CR1 |= USART_CR1_RXNEIE;

    NVIC_EnableIRQ(USART2_IRQn);

    USART2->CR1 |= USART_CR1_UE; // Включение UART
}

// Реализация функции задержки (опционально)
void delay_ms(uint32_t ms) {
    for (volatile uint32_t i = 0; i < ms * 8000; i++) {
        __NOP();
    }
}

int main(void) {

    SystemCoreClockUpdate(); // Обновление системной частоты (если нужно)
    init_usart();// Инициализация USART2

    const char *msg = "USART2 Initialized!\r\n"; // Отправка приветственного сообщения

    while (*msg) {
        // Передача данных по USART
        while (!(USART2->ISR & USART_ISR_TXE)); // ждем, пока буфер не освободится
        USART2->TDR = *msg++;
    }

    // Отправка значения SystemCoreClock
    char buffer[50];
    snprintf(buffer, sizeof(buffer), "SystemCoreClock = %u Hz\r\n", (unsigned int)SystemCoreClock);

    const char *ptr = buffer;
    while (*ptr) {
        while (!(USART2->ISR & USART_ISR_TXE)); // ждем готовности буфера передачи
        USART2->TDR = *ptr++;
    }

    while (1) {
        // Основной цикл - можно реализовать другие задачи
        // Например, ждать прерываний или отправлять данные
    }
}

// Обработчик прерываний для USART2
void USART2_IRQHandler(void) {
    if (USART2->ISR & USART_ISR_RXNE) {
        uint8_t data = USART2->RDR; // чтение полученных данных

        // Обработка полученных данных...
        (void)data; // чтобы избежать предупреждения о неиспользуемой переменной
    }
}




